'use strict';

/**
 * Bank lists for NTD (Taiwan) and IDR (Indonesia) accounts.
 * Single source of truth — replaces frontend lib/banks.ts.
 *
 * Shape: each entry is { code, name, display_label } so consumers can render uniformly.
 * - NTD: numeric code + bilingual name.
 * - IDR: code === name (no numeric codes; bank chosen by name).
 */

const NTD_BANKS = [
  { code: '004', name: 'Bank of Taiwan (臺灣銀行)' },
  { code: '005', name: 'Land Bank of Taiwan (土地銀行)' },
  { code: '006', name: 'Taiwan Cooperative Bank (合庫商銀)' },
  { code: '007', name: 'First Commercial Bank (第一銀行)' },
  { code: '008', name: 'Hua Nan Commercial Bank (華南銀行)' },
  { code: '009', name: 'Chang Hwa Commercial Bank (彰化銀行)' },
  { code: '011', name: 'The Shanghai Commercial & Savings Bank (上海銀行)' },
  { code: '012', name: 'Taipei Fubon Bank (台北富邦)' },
  { code: '013', name: 'Cathay United Bank (國泰世華)' },
  { code: '016', name: 'Bank of Kaohsiung (高雄銀行)' },
  { code: '017', name: 'Mega International Commercial Bank (兆豐商銀)' },
  { code: '018', name: 'AGRI Bank (農業金庫)' },
  { code: '021', name: 'Citibank (花旗(台灣)銀行)' },
  { code: '022', name: 'Bank of America (美國銀行)' },
  { code: '025', name: 'Metro Bank (首都銀行)' },
  { code: '039', name: 'ANZ Taiwan (澳盛(台灣)銀行)' },
  { code: '040', name: 'China Development Industrial Bank (中華開發)' },
  { code: '048', name: 'O-Bank (王道銀行)' },
  { code: '050', name: 'Taiwan Business Bank (臺灣企銀)' },
  { code: '052', name: 'Standard Chartered Bank Taiwan (渣打國際商銀)' },
  { code: '053', name: 'Taichung Commercial Bank (台中商銀)' },
  { code: '054', name: "King's Town Bank (京城商銀)" },
  { code: '072', name: 'Deutsche Bank (德意志銀行)' },
  { code: '075', name: 'Bank of East Asia (東亞銀行)' },
  { code: '081', name: 'HSBC (滙豐(台灣))' },
  { code: '082', name: 'BNP Bank Taiwan (法國巴黎銀行台北分行)' },
  { code: '101', name: 'Bank of Taipei (瑞興銀行)' },
  { code: '102', name: 'Hua Tai Commercial Bank (華泰銀行)' },
  { code: '103', name: 'Taiwan Shikon Commercial Bank (臺灣新光商銀)' },
  { code: '104', name: 'The Fifth Credit Cooperative of Taipei (台北五信)' },
  { code: '108', name: 'Sunny Bank (陽信銀行)' },
  { code: '114', name: 'Keelung First Credit Cooperative (基隆一信)' },
  { code: '115', name: 'Keelung Second Credit Cooperative (基隆二信)' },
  { code: '118', name: 'Bank of Panhsin (板信銀行)' },
  { code: '119', name: 'The Damshui First Credit Cooperative Bank (淡水一信)' },
  { code: '120', name: 'The Damshui Credit Cooperative (淡水信合社)' },
  { code: '124', name: 'The Credit Cooperative of Ilan (宜蘭信合社)' },
  { code: '127', name: 'The Credit Cooperative of Taoyuan (桃園信合社)' },
  { code: '130', name: 'The First Credit Cooperative of Hsinchu (新竹一信)' },
  { code: '132', name: 'The Third Credit Cooperative of Hsinchu (新竹三信)' },
  { code: '146', name: 'The Second Credit Cooperative of Taichung (台中二信)' },
  { code: '147', name: 'Coat Commercial Bank (三信銀行)' },
  { code: '158', name: 'The First Credit Cooperative of Chung Hua (彰化一信)' },
  { code: '161', name: 'The Fifth Credit Cooperative of Chung Hua (彰化五信)' },
  { code: '162', name: 'The Sixth Credit Cooperative of Chung Hua (彰化六信)' },
  { code: '163', name: 'The Tenth Credit Cooperative of Chung Hua (彰化十信)' },
  { code: '165', name: 'The Credit Cooperative of Lu Kang (鹿港信合社)' },
  { code: '178', name: 'The Third Credit Cooperative of Chiayi (嘉義三信)' },
  { code: '188', name: 'Tainan Credit Cooperative (台南三信)' },
  { code: '204', name: 'The Kaohsiung Third Credit Cooperative (高雄三信)' },
  { code: '215', name: 'Hualien First Credit Cooperative (花蓮一信)' },
  { code: '216', name: 'Hualien Second Credit Cooperative (花蓮二信)' },
  { code: '222', name: 'Penghu First Credit Cooperative (澎湖一信)' },
  { code: '223', name: 'Penghu Second Credit Cooperative (澎湖二信)' },
  { code: '224', name: 'Kinmen Credit Cooperative (金門信合社)' },
  { code: '512', name: "Yunlin District Fishermen's Association (雲林漁會)" },
  { code: '515', name: "Chiayi District Fishermen's Association (嘉義漁會)" },
  { code: '517', name: "Nansh District Fishermen's Association (南市區漁會)" },
  { code: '518', name: "Nansian District Fishermen's Association (南縣漁會)" },
  { code: '520', name: "Xiaogang Dist. Fishermen's Association (小港區漁會)" },
  { code: '521', name: "Kaohsiung County YongAn Dist. Fishermen's Association (高雄縣永安區漁會)" },
  { code: '523', name: "Pingtung Farmers' Association (屏東港漁會)" },
  { code: '524', name: "Singang District Fishermen's Association (新港漁會)" },
  { code: '525', name: "Fishermen's Association of Penghu (澎湖區漁會)" },
  { code: '600', name: 'Naffic (財團法人全國農漁業及金融資訊中心)' },
  { code: '605', name: "The Kaohsiung City Farmers' Association (高雄市農會)" },
  { code: '612', name: "Fengyuan Dist. Farmers' Association (豐原區農會)" },
  { code: '613', name: "Mingjian Township Farmers' Association (名間農會)" },
  { code: '614', name: "Changhua County Farmers' Association (彰化縣農會)" },
  { code: '616', name: "Southern Farmers' Association (南農中心)" },
  { code: '617', name: "Chiayi Farmers' Association (嘉義農會)" },
  { code: '618', name: "Guiren Township Farmers' Association (歸仁鄉農會)" },
  { code: '619', name: "Ziguan Township Farmers' Association (梓官鄉農會)" },
  { code: '620', name: "Pingtung County Farmers' Association (屏東縣農會)" },
  { code: '621', name: "Shoufeng Township Farmers' Association (壽豐鄉農會)" },
  { code: '622', name: "Taitung Area Farmers' Association (台東區農會)" },
  { code: '624', name: "Penghu Township Farmers' Association (澎湖農會)" },
  { code: '625', name: "Taichung Township Farmers' Association (台中市農會)" },
  { code: '627', name: "Lienchian Township Farmers' Association (連江縣農會)" },
  { code: '700', name: 'Chunghwa Post (中華郵政)' },
  { code: '803', name: 'Union Bank of Taiwan (聯邦銀行)' },
  { code: '805', name: 'Far Eastern International Bank (遠東銀行)' },
  { code: '806', name: 'Yuanta Bank (元大銀行)' },
  { code: '807', name: 'Bank SinoPac (永豐銀行)' },
  { code: '808', name: 'E.Sun Bank (玉山銀行)' },
  { code: '809', name: 'KGI Bank (凱基銀行)' },
  { code: '810', name: 'DBS Bank Taiwan (星展銀行(台灣))' },
  { code: '812', name: 'Taishin Bank (台新銀行)' },
  { code: '814', name: 'Ta Chong Bank (大眾銀行)' },
  { code: '815', name: 'Jih Sun International Bank (日盛銀行)' },
  { code: '816', name: 'En Tie Bank (安泰銀行)' },
  { code: '822', name: 'Chinatrust Commercial Bank (中國信託)' },
  { code: '901', name: "Dali Township Farmers' Association (大里農會)" },
  { code: '903', name: "Sijhih Township Farmers' Association (汐止農會)" },
  { code: '904', name: "Sinjhuang Township Farmers' Association (新莊農會)" },
  { code: '910', name: "Taoyuan Farmers' Association (桃農共用中心)" },
  { code: '912', name: "Dongsan Township Farmer's Association (冬山農會)" },
  { code: '916', name: "Tsaotun Township Farmer's Association (草屯農會)" },
  { code: '922', name: "Tainan City Farmer's Association (台南市農會)" },
  { code: '928', name: "Panchiao Farmer's Association (板橋農會)" },
  { code: '951', name: "Northern Farmers' Association (北區農會)" },
  { code: '952', name: "South Farmers' Association (財團法人農漁會南區資訊中心)" },
  { code: '954', name: "Central Farmers' Association (中區農會)" },
  { code: '997', name: 'SCU South Credit Union (中華民國信用合作社聯合社南區聯合資訊處理中心)' },
];

const IDR_BANK_NAMES = [
  'PT BANK RAKYAT INDONESIA (PERSERO) Tbk',
  'PT BANK MANDIRI (PERSERO) Tbk',
  'PT BANK NEGARA INDONESIA (PERSERO) Tbk',
  'PT BANK TABUNGAN NEGARA (PERSERO) Tbk',
  'PT BANK CENTRAL ASIA Tbk',
  'PT BANK CIMB NIAGA Tbk',
  'PT BANK DANAMON INDONESIA Tbk',
  'PT BANK PERMATA Tbk',
  'PT BANK MAYBANK INDONESIA Tbk',
  'PT BANK PAN INDONESIA Tbk',
  'PT BANK UOB INDONESIA',
  'PT BANK OCBC NISP Tbk',
  'PT BANK ARTHA GRAHA INTERNASIONAL Tbk',
  'PT BANK BUMI ARTA Tbk',
  'PT BANK HSBC INDONESIA',
  'PT BANK JTRUST INDONESIA Tbk',
  'PT BANK MAYAPADA INTERNATIONAL Tbk',
  'PT BANK OF INDIA INDONESIA Tbk',
  'PT BANK MUAMALAT INDONESIA Tbk',
  'PT BANK MESTIKA DHARMA Tbk',
  'PT BANK SHINHAN INDONESIA',
  'PT BANK SINARMAS Tbk',
  'PT BANK MASPION INDONESIA Tbk',
  'PT BANK GANESHA Tbk',
  'PT BANK ICBC INDONESIA',
  'PT BANK QNB INDONESIA Tbk',
  'PT BANK WOORI SAUDARA INDONESIA 1906 Tbk',
  'PT BANK MEGA Tbk',
  'PT BANK KB BUKOPIN Tbk',
  'PT BANK SYARIAH INDONESIA Tbk',
  'PT BANK KEB HANA INDONESIA',
  'PT BANK MNC INTERNASIONAL Tbk',
  'PT BANK RAYA INDONESIA Tbk',
  'PT BANK SBI INDONESIA',
  'PT BANK MEGA SYARIAH',
  'PT BANK INDEX SELINDO',
  'PT BANK HIBANK INDONESIA',
  'PT BANK CHINA CONSTRUCTION BANK INDONESIA Tbk',
  'PT BANK DBS INDONESIA',
  'PT BANK RESONA PERDANIA',
  'PT BANK MIZUHO INDONESIA',
  'PT BANK CAPITAL INDONESIA Tbk',
  'PT BANK BNP PARIBAS INDONESIA',
  'PT BANK ANZ INDONESIA',
  'PT BANK IBK INDONESIA Tbk',
  'PT BANK ALADIN SYARIAH Tbk',
  'PT BANK CTBC INDONESIA',
  'PT BANK COMMONWEALTH',
  'PT BANK TABUNGAN PENSIUNAN NASIONAL Tbk',
  'PT BANK VICTORIA SYARIAH',
  'PT BANK JABAR BANTEN SYARIAH',
  'PT KROM BANK INDONESIA Tbk',
  'PT BANK JASA JAKARTA',
  'PT BANK NEO COMMERCE Tbk',
  'PT BANK DIGITAL BCA',
  'PT BANK NATIONALNOBU Tbk',
  'PT BANK INA PERDANA Tbk',
  'PT BANK PANIN DUBAI SYARIAH Tbk',
  'PT BANK KB BUKOPIN SYARIAH',
  'PT BANK SAHABAT SAMPOERNA',
  'PT BANK OKE INDONESIA Tbk',
  'PT BANK AMAR INDONESIA',
  'PT BANK SEABANK INDONESIA',
  'PT BANK BCA SYARIAH',
  'PT BANK JAGO TBK',
  'PT BANK BTPN SYARIAH Tbk',
  'PT BANK MULTIARTA SENTOSA Tbk',
  'PT SUPER BANK INDONESIA',
  'PT BANK MANDIRI TASPEN',
  'PT BANK VICTORIA INTERNATIONAL Tbk',
  'PT ALLO BANK INDONESIA Tbk',
  'PT BANK NANO SYARIAH',
  'PT BPD JAWA BARAT DAN BANTEN Tbk',
  'PT BPD DKI',
  'PT BPD DAERAH ISTIMEWA YOGYAKARTA',
  'PT BPD JAWA TENGAH',
  'PT BPD JAWA TIMUR Tbk',
  'PT BPD JAMBI',
  'PT BANK ACEH SYARIAH',
  'PT BPD SUMATERA UTARA',
  'PT BANK NAGARI',
  'PT BPD RIAU KEPRI SYARIAH',
  'PT BPD SUMATERA SELATAN DAN BANGKA BELITUNG',
  'PT BPD LAMPUNG',
  'PT BPD KALIMANTAN SELATAN',
  'PT BPD KALIMANTAN BARAT',
  'PT BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA',
  'PT BPD KALIMANTAN TENGAH',
  'PT BPD SULAWESI SELATAN DAN SULAWESI BARAT',
  'PT BPD SULAWESI UTARA DAN GORONTALO',
  'PT BANK NTB SYARIAH',
  'PT BPD BALI',
  'PT BPD NUSA TENGGARA TIMUR',
  'PT BPD MALUKU DAN MALUKU UTARA',
  'PT BPD PAPUA',
  'PT BPD BENGKULU',
  'PT BPD SULAWESI TENGAH',
  'PT BPD SULAWESI TENGGARA',
  'PT BPD BANTEN Tbk',
  'CITIBANK N.A.',
  'JP MORGAN CHASE BANK NA',
  'BANK OF AMERICA N.A',
  'MUFG BANK LTD',
  'STANDARD CHARTERED BANK',
  'DEUTSCHE BANK AG',
  'BANK OF CHINA (HONG KONG) LIMITED CABANG JAKARTA',
];

function decorate(rec, currency) {
  if (currency === 'NTD') {
    return { code: rec.code, name: rec.name, display_label: `${rec.code} — ${rec.name}` };
  }
  // IDR: name acts as code (no separate numeric code)
  return { code: rec, name: rec, display_label: rec };
}

function listBanks(currency) {
  if (currency === 'NTD') return NTD_BANKS.map((b) => decorate(b, 'NTD'));
  if (currency === 'IDR') return IDR_BANK_NAMES.map((b) => decorate(b, 'IDR'));
  return null;
}

function getBankName(code, currency) {
  if (!code) return null;
  if (currency === 'NTD') {
    const found = NTD_BANKS.find((b) => b.code === code);
    return found ? found.name : null;
  }
  if (currency === 'IDR') {
    return IDR_BANK_NAMES.includes(code) ? code : null;
  }
  return null;
}

module.exports = { listBanks, getBankName };
